(dp1
S'output'
p2
S"<class '_mysql_exceptions.OperationalError'> (1075, 'Incorrect table definition; there can be only one auto column and it must be defined as a key')"
p3
sS'layer'
p4
S'/opt/web2py/applications/know_your_world/models/db.py'
p5
sS'code'
p6
S"db = DAL('mysql://root:wtfcall911@localhost/factbook')\ndb.define_table('sdata',\n                Field('country_id',unique=True),\n                Field('country'),\n                Field('data','big-id'))\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/opt/web2py/gluon/restricted.py", line 212, in restricted\n    exec ccode in environment\n  File "/opt/web2py/applications/know_your_world/models/db.py", line 5, in <module>\n    Field(\'data\',\'big-id\'))\n  File "/opt/web2py/gluon/dal.py", line 7644, in define_table\n    table = self.lazy_define_table(tablename,*fields,**args)\n  File "/opt/web2py/gluon/dal.py", line 7681, in lazy_define_table\n    polymodel=polymodel)\n  File "/opt/web2py/gluon/dal.py", line 988, in create_table\n    fake_migrate=fake_migrate)\n  File "/opt/web2py/gluon/dal.py", line 1091, in migrate_table\n    self.execute(sub_query)\n  File "/opt/web2py/gluon/dal.py", line 1756, in execute\n    return self.log_execute(*a, **b)\n  File "/opt/web2py/gluon/dal.py", line 1750, in log_execute\n    ret = self.cursor.execute(*a, **b)\n  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute\n    self.errorhandler(self, exc, value)\n  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\nOperationalError: (1075, \'Incorrect table definition; there can be only one auto column and it must be defined as a key\')\n'
p11
s.